# Tell Flux which container registry to scan for new tags
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: rust-echo
  namespace: flux-system
spec:
  image: jordanyong/rust-echo
  interval: 1m0s