# Tell Flux which semver range to use when filtering tags
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: rust-echo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rust-echo
  filterTags:
    pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc