apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-01
  namespace: express-01
spec:
  selector:
    matchLabels:
      app: express-01
  replicas: 1
  template:
    metadata:
      labels:
        app: express-01
    spec:
      containers:
      - name: express-01
        image: jordanyong/express-01:main-ed4920ce11fb300cad84b27ae43d81772f55fff4-8 # {"$imagepolicy": "flux-system:express-01"}
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1"
          requests:
            memory: "500Mi"
            cpu: "0.5"
