---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-01
  namespace: express-01
spec:
  selector:
    matchLabels:
      app: express-01
  replicas: 1
  template:
    metadata:
      labels:
        app: express-01
    spec:
      containers:
      - name: express-01
        image: jordanyong/express-01:main-0d3f1390a9df4943f4fd8421a616e5be81653c05-7 # {"$imagepolicy": "flux-system:express-01"}
        ports:
        - containerPort: 80