apiVersion: v1
kind: Namespace
metadata:
  name: express-01
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-01
  namespace: express-01
spec:
  selector:
    matchLabels:
      app: express-01
  replicas: 1
  template:
    metadata:
      labels:
        app: express-01
    spec:
      containers:
      - name: express-01
        image: jordanyong/express-01:main-0d3f1390a9df4943f4fd8421a616e5be81653c05-7 # {"$imagepolicy": "flux-system:express-01"}
        ports:
        - containerPort: 80
---
# Tell Flux which container registry to scan for new tags
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: express-01
  namespace: flux-system
spec:
  image: jordanyong/express-01
  interval: 1m0s
---
# Tell Flux which semver range to use when filtering tags
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: express-01
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: express-01
  filterTags:
    pattern: '^main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
