apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-02
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo-02
  template:
    metadata:
      labels:
        app: podinfo-02
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.3 # {"$imagepolicy": "flux-system:podinfo"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
